# Cafe data EDA to find out the realtion between
* Quantity and Price Per Unit impact on total spend
* Total Spent by Transaction Date
* Total Spent against Location
* Total Spent against Payment Method

# Library we will need

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as st
import warnings
warnings.filterwarnings('ignore')

## Load data

In [3]:
df = pd.read_csv('clean_cafe_data.csv')
df.head(10)

,Transaction ID,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,4,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,5,4.0,20.0,Credit Card,UNKNOWN,2023-03-31
6,TXN_4433211,3,3.0,9.0,UNKNOWN,Takeaway,2023-10-06
7,TXN_6699534,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,5,3.0,15.0,UNKNOWN,Takeaway,2023-07-28
9,TXN_2064365,5,4.0,20.0,UNKNOWN,In-store,2023-12-31

In [5]:
df.shape

(10000, 7)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Quantity          10000 non-null  int64
 2   Price Per Unit    10000 non-null  float64
 3   Total Spent       10000 non-null  float64
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 547.0+ KB

## Extracted new column from the transaction date, called day of week

In [13]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df['Day_of_Week'] = df['Transaction Date'].dt.day_name()

In [14]:
df.head(10)

,Transaction ID,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Day_of_Week
0,TXN_1961373,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,Friday
1,TXN_4977031,4,3.0,12.0,Cash,In-store,2023-05-16,Tuesday
2,TXN_4271903,4,1.0,8.9,Credit Card,In-store,2023-07-19,Wednesday
3,TXN_7034554,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,Thursday
4,TXN_3160411,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,Sunday
5,TXN_2602893,5,4.0,20.0,Credit Card,UNKNOWN,2023-03-31,Friday
6,TXN_4433211,3,3.0,9.0,UNKNOWN,Takeaway,2023-10-06,Friday
7,TXN_6699534,4,4.0,16.0,Cash,UNKNOWN,2023-10-28,Saturday
8,TXN_4717867,5,3.0,15.0,UNKNOWN,Takeaway,2023-07-28,Friday
9,TXN_2064365,5,4.0,20.0,UNKNOWN,In-store,2023-12-31,Sunday

In [15]:
df = df[['Quantity' , 'Price Per Unit' ,	'Total Spent' , 'Payment Method' , 'Location' , 'Day_of_Week']]

In [18]:
df.isnull().sum()

Quantity          0
Price Per Unit    0
Total Spent       0
Payment Method    0
Location          0
Day_of_Week       0
dtype: int64

## Lets check quantity and price per unit impact on Total spent

In [30]:
df['Day_of_Week'].value_counts(normalize = True)

Day_of_Week
Monday       0.1453
Friday       0.1448
Sunday       0.1437
Thursday     0.1436
Saturday     0.1432
Wednesday    0.1415
Tuesday      0.1379
Name: proportion, dtype: float64

In [31]:
df['Payment Method'].value_counts(normalize = True)

Payment Method
UNKNOWN           0.3178
Digital Wallet    0.2291
Credit Card       0.2273
Cash              0.2258
Name: proportion, dtype: float64

In [32]:
df['Location'].value_counts(normalize = True)

Location
UNKNOWN     0.3961
Takeaway    0.3022
In-store    0.3017
Name: proportion, dtype: float64

In [29]:
df.describe()

           Quantity  Price Per Unit   Total Spent
count  10000.000000     10000.00000  10000.000000
mean       3.027100         2.94732      8.923130
std        1.384614         1.24396      5.857115
min        1.000000         1.00000      1.000000
25%        2.000000         2.00000      4.000000
50%        3.000000         3.00000      8.000000
75%        4.000000         4.00000     12.000000
max        5.000000         5.00000     25.000000